### ISSUE TITLE
Update the release to latest (Zig 0.8.0 build)  

### ISSUE THREAD

**Issue by VarLad** [zigtools/zls#347]

**Comment by leecannon** [comment]
@alexnask Maybe going forward a tag could be made for every release of zig?
So building zls against a stable (as stable as pre-1.0 version can be) zig is easy.

**Comment by VarLad** [comment]
Nice idea

But is it possible to build for 0.8?

**Comment by leecannon** [comment]
You would have to use an old commit that works with 0.8.0

As zig 0.8.0 was released 2021-06-04 that would be either b756ed4da59cb0ec419a4010ab6f870c1924924f or the commit just before it (im unsure if the HashMap breaking change made it in time for 0.8.0)

**Comment by gitonthescene** [comment]
FWIW, I installed v0.8.0 with macports and I was getting this error:

``` sh
$ zig build -Drelease-safe
./build.zig:18:59: error: no member named 'path' in '[]const u8'
    exe.addPackage(.{ .name = "known-folders", .path = .{ .path = "src/known-folders/known-folders.zig" } });
                                                          ^
/opt/local/lib/zig/std/special/build_runner.zig:158:24: note: referenced here
        .ErrorUnion => try root.build(builder),
$
```

Per the suggestion above, the following seems to work:

``` sh
$ clone --recurse-submodules https://github.com/zigtools/zls         
Cloning into 'zls'...
remote: Enumerating objects: 3242, done.
...
Submodule path 'src/known-folders': checked out '3385a8b2317b8f438fa933e1683237254cfc5d71'
Submodule path 'src/zinput': checked out '95106b1f71430f61973f81f7b255f3b319d88828'
$ ~ cd zls 
$ git fetch origin b756ed4da59cb0ec419a4010ab6f870c1924924f
From https://github.com/zigtools/zls
 * branch            b756ed4da59cb0ec419a4010ab6f870c1924924f -> FETCH_HEAD
$ git reset --hard FETCH_HEAD
HEAD is now at b756ed4 Fixed HashMap usage for latest master stdlib
$ zig build -Drelease-safe                                 
LLVM Emit Object... 
$ 
```

I also think tagging is a great idea.

**Comment by nektro** [comment]
ZLS `master` will continue to track Zig `master` but I will add tags when Zig releases new versions going forward as suggested in this thread.

**Comment by jbeich** [comment]
[0.2.0 release](https://github.com/zigtools/zls/releases/tag/0.2.0) still fails to build with Zig 0.8.1 (current stable). Zig version (`master` is a moving target) used to build the binaries doesn't appear to be documented. And the binaries cannot be used on anything less common like Linux aarch64 or FreeBSD x86_64.
```zig
./build.zig:10:26: error: no member named 'addOptions' in struct 'std.build.Builder'
    const exe_options = b.addOptions();
                         ^
/usr/lib/zig/std/special/build_runner.zig:170:24: note: referenced here
        .ErrorUnion => try root.build(builder),
                       ^
```

**Comment by SuperAuguste** [comment]
zls must be built using Zig master.

**Comment by jbeich** [comment]
> zls must be built using Zig master.

`master` is a moving target. What I'm supposed to do if zls-0.2.0 fails to build with Zig `master` the next month?

**Comment by SuperAuguste** [comment]
> What I'm supposed to do if zls-0.2.0 fails to build with Zig `master` the next month?
Use the latest commit of zls with the latest commit of zig? They're meant to go hand-in-hand. zls releases exist moreso for the executables than the sources :)

**Comment by jbeich** [comment]
> Use the latest commit of zls with the latest commit of zig?

Why create tags if builds are not reproducible?

> zls releases exist moreso for the executables than the sources :)

Current tags don't have executables for my platform (FreeBSD).  And downstream (for building system packages) needs to know which Zig versions were tested upstream.

**Comment by jbeich** [comment]
https://www.freshports.org/devel/zls is an example downstream. It builds fine with Zig 0.8.1 but tracking down the last usable zls commit was very error-prone.

**Comment by SuperAuguste** [comment]
I will start tagging zls releases by release then and emit a new one once 0.9.0 comes out. Thank you.
