### ISSUE TITLE
Build fails with -Drelease-safe (zig: master)

### ISSUE THREAD

**Issue by meinside** [zigtools/zls#413]
Hi, I cannot get zls built with the guide in the [README.md](https://github.com/zigtools/zls#from-source).

With `zig build -Drelease-safe`, it fails with:

```
./src/main.zig:34:39: error: expected type 'std.log.Level', found '.build_options.Level'
var actual_log_level: std.log.Level = switch (zig_builtin.mode) {
                                      ^
/opt/zig-master/lib/zig/std/log.zig:75:19: note: std.log.Level declared here
pub const Level = enum {
                  ^
./zig-cache/options/L9eqxgIAE4PmL1q7z-R9mddPxCA1hxdCO2SbWbMoIU3gyy2e0E0-nMjqqyAeR5Ke:9:19: note: .build_options.Level declared here
pub const Level = enum {
                  ^
./src/main.zig:1674:13: note: referenced here
            actual_log_level = .debug;
            ^
zls...The following command exited with error code 1:
/opt/zig-master/zig build-exe /opt/zls/src/main.zig -OReleaseSafe --cache-dir /opt/zls/zig-cache --global-cache-dir /home/xxxxxx/.cache/zig --name zls --pkg-begin build_options /opt/zls/zig-cache/options/L9eqxgIAE4PmL1q7z-R9mddPxCA1hxdCO2SbWbMoIU3gyy2e0E0-nMjqqyAeR5Ke --pkg-end --pkg-begin known-folders /opt/zls/src/known-folders/known-folders.zig --pkg-end --pkg-begin zinput /opt/zls/src/zinput/src/main.zig --pkg-end --enable-cache
error: the following build command failed with exit code 1:
/opt/zls/zig-cache/o/58bf96d7a4a2c76b15e2706b274983b2/build /opt/zig-master/zig /opt/zls /opt/zls/zig-cache /home/xxxxxx/.cache/zig -Drelease-safe
```

but builds OK with just `zig build`.

Zig version: 0.9.0-dev.1561+5ebdc8c46
ZLS version: 4d6d842

What could be the problem? What am I missing?

**Comment by nektro** [comment]
hmm this wouldv'e been caused by #412, looks to be a Zig bug

**Comment by omaraaa** [comment]
can be fixed with this change:
```zig
var actual_log_level: std.log.Level = switch (zig_builtin.mode) {
    .Debug => .debug,
    else => @intToEnum(std.log.Level, @enumToInt(build_options.log_level)),
};
```

**Comment by meinside** [comment]
Thank you for the fix!

**Comment by InKryption** [comment]
I'm unsure of whether this is worthy of opening an issue of its own, but the change in #414 seems to have created an issue, at least using Visual Studio, where it logs debug error messages even with `-Drelease={not debug} -Dlog_level={not debug}`. And it's logging so much that it's causing pretty me severe slow downs for my slightly bigger projects, or whenever I look through `std`. I tracked the problem down to here: https://github.com/zigtools/zls/blob/d4b6b97c019972de6e4fd710045d2b9349147ad3/src/main.zig#L40

Which I figure, because when I change the clause to:
`(@enumToInt(message_level) > @enumToInt(actual_log_level) and message_level != .debug) or message_level == .debug`, it no longer bombards me with a constant stream of debug messages, whilst still logging things like when it starts up or when it shuts down.

Please someone here tell me if I'm missing something or that I've somehow done something wrong.

**Comment by omaraaa** [comment]
> 
> 
> I'm unsure of whether this is worthy of opening an issue of its own, but the change in #414 seems to have created an issue, at least using Visual Studio, where it logs debug error messages even with `-Drelease={not debug} -Dlog_level={not debug}`. And it's logging so much that it's causing pretty me severe slow downs for my slightly bigger projects, or whenever I look through `std`. I tracked the problem down to here:
> 
> https://github.com/zigtools/zls/blob/d4b6b97c019972de6e4fd710045d2b9349147ad3/src/main.zig#L40
> 
> Which I figure, because when I change the clause to: `(@enumToInt(message_level) > @enumToInt(actual_log_level) and message_level != .debug) or message_level == .debug`, it no longer bombards me with a constant stream of debug messages, whilst still logging things like when it starts up or when it shuts down.
> 
> Please someone here tell me if I'm missing something or that I've somehow done something wrong.
> 
> Edit: setting `-Dlog_level=warn` as suggested in #412, which I just saw, does not appear to fix this either.

try both `-Drelease-fast` and `-Dlog_level=warn`, it should produce no notification on VSCode.

**Comment by InKryption** [comment]
@omaraaa That is one of the combinations I've tried, and it still gives way to the issue, where `log` never returns early (before logging), no matter the log level.

**Comment by omaraaa** [comment]
`(@enumToInt(message_level) > @enumToInt(actual_log_level) and message_level != .debug) or message_level == .debug` would just return early in all logging levels. It's seems the issue is that logging uses `"window/showMessage"` instead of `"window/logMessage"`. #415 will hopefully fix the performance issues in VSCode.

**Comment by InKryption** [comment]
@omaraaa I see, that would make more sense, as it didn't stop VSCode from showing messages prefixed as "info", like "info-main: Using zig executable {path}" and the like. Thanks for the fix.
