### ISSUE TITLE
array_list.insertSlice API change in zig std library breaks build for all zls 0.13.x commits

### ISSUE THREAD

**Issue by timblaktu** [zigtools/zls#1894]
### Zig Version

0.13.0-dev.156+661a9be66

### Zig Language Server Version

cc98286..bb19bee (all commits after 0.12.0 tag)

### Client / Code Editor / Extensions

none, n/A

### Steps to Reproduce and Observed Behavior

As in PR #1887, there remain incompatibilities between zig master and zls master. I am simply trying to build zls for the first time, and after my first attempt said my zig version was out of date, I upgraded building zig master HEAD commit [661a9be](https://github.com/ziglang/zig/commit/661a9be66bdee78530e5a6fbb6463297a405beee) from source. Using this version, I am getting the following error when building any zls commit after the 0.12.0 release tag, starting with `cc98286` up to current HEAD (`bb19bee`):

```
[0]tim@sector17g-debian:~/src/zls
> git checkout cc98286 && zig build -Doptimize=ReleaseSafe                                                                  zls (remotes/origin/techatrix/new-build-runner~5) % (⎈|BINARY-N/A:N/A)
HEAD is now at cc98286 begin the 0.13.0 release cycle
/home/tim/src/zls/build.zig:294:23: error: member function expected 3 argument(s), found 2
        tests_run.argv.insertSlice(0, args) catch @panic("OOM");
        ~~~~~~~~~~~~~~^~~~~~~~~~~~
/usr/local/lib/zig/std/array_list.zig:781:13: note: function declared here
        pub fn insertSlice(
        ~~~~^~
referenced by:
    runBuild__anon_8768: /usr/local/lib/zig/std/Build.zig:2079:37
    main: /usr/local/lib/zig/compiler/build_runner.zig:300:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
/home/tim/.cache/zig/p/12200d71e4b7029ea56a429e24260c6c0e85a3069b0d4ba85eace21a0fd75910aa64/build.zig:5:33: error: no field named 'path' in union 'Build.LazyPath'
        .root_source_file = .{ .path = "DiffMatchPatch.zig" },
                                ^~~~
/usr/local/lib/zig/std/Build.zig:2133:22: note: union declared here
pub const LazyPath = union(enum) {
                     ^~~~~
/home/tim/.cache/zig/p/12201314cffeb40c5e4e3da166217d2c74628c74486414aaf97422bcd2279915b9fd/build.zig:5:33: error: no field named 'path' in union 'Build.LazyPath'
        .root_source_file = .{ .path = "known-folders.zig" },
                                ^~~~
/usr/local/lib/zig/std/Build.zig:2133:22: note: union declared here
pub const LazyPath = union(enum) {
                     ^~~~~
```

This appears to be caused by an API change in the `insertSlice` method in the zig std library. I haven't tracked this down yet, as I figured this to be a general problem and as a newbie here.

What is the process for managing / syncing zig/zls versions?

Surely users aren't expected to `git bisect` their zig installations to find the breaking commit and install/use a prior commit. 

This is clearly a job for CI - is there any "`zig` version/API detection and reporting" built into zls CI?

### Expected Behavior

ZLS commits should `zig build` successfully, or detect zig version incompatibility and inform user.

**Comment by Techatrix** [comment]
This will be fixed by #1892. It can be merged once Zig's upstream binaries at https://ziglang.org/download/ have updated. The latest Zig version available is `0.13.0-dev.75+5c9eb4081` which successfully compiles ZLS.

**Comment by timblaktu** [comment]
OK, thanks for that reference and info @Techatrix. I interpret this that I should be able to install that zig version from source and the error would go away. 

This implies the zls dev process is only synced with the zig dev process at release milestones. That's fine but I wonder if there's not some additional help that could be offered for those building from source and wanting to contribute. E.g. have you considered adding a CI that can track compatibility between zig commits and zls commits and publish the matrix somewhere for easy public view?

**Comment by Techatrix** [comment]
> I interpret this that I should be able to install that zig version from source and the error would go away.

Not sure why the need to compile from source but yes. I checked it when I wrote my comment.

> This implies the zls dev process is only synced with the zig dev process at release milestones.

No, ZLS's master branch targets Zig's master branch. We also release [tagged releases](https://github.com/zigtools/zls/releases) for every [tagged release](https://github.com/ziglang/zig/releases) of Zig.

---

When Zig introduces a breaking change, the following will happen (in order): 
The following will happen (in order):
-  Everyone who compiles the latest Zig from source will be instantly hit. 
- Zig's [CI](https://github.com/ziglang/www.ziglang.org/actions/runs/9043497143) has built new binaries (which happens every six hours usually). Everyone who install upstream binaries will be hit. 
- ZLS updates to fix the issue

Any CI based tool wouldn't be able to help you because it only gets hit once upstream binaries have updated.

You just managed to hit the perfect timing by compiling Zig from source while a breaking change occurred which is not yet in the latest upstream binary.

> I wonder if there's not some additional help that could be offered for those building from source and wanting to contribute.

ZLS's build.zig stores the [minimum Zig version](https://github.com/zigtools/zls/blob/bb19beeb38a8c3df9a2408b8e15664415b8347ef/build.zig#L13) that is required to compile ZLS from source. That version is guaranteed to be able to compile ZLS.

---

The story is different when dealing with upstream binaries of ZLS instead of compiling from source. This is something where I am currently working on to improve the user experience.

**Comment by timblaktu** [comment]
Thanks so much for the explanation, @Techatrix! 

What I was imagining was that the zls CI would be triggered by zig and zls commits, so that each zls commit could be validated against all zig commits, creating the compatibility matrix for devs.

Not saying this is worth your time, esp knowing what you've shared with me. Thanks again.

**Comment by timblaktu** [comment]
FWIW, after cleanly rebuilding zig from that commit you referenced, in my case:

`git checkout 5c9eb40816 && git clean -d -f -x && mkdir -p build && (cd build; cmake -DCMAKE_PREFIX_PATH=$HOME/local/llvm17-release .. && time make -j8 install)`

I still get the same error originally reported when cleanly rebuilding zls:

```
 [0]tim@sector17g-debian:~/src/zls
> git checkout master                                                                                                                                            
Already on 'master'
Your branch is up to date with 'origin/master'.
 [0]tim@sector17g-debian:~/src/zls
> zig version                                                                                                                                                    
0.13.0-dev.75+5c9eb4081
 [0]tim@sector17g-debian:~/src/zls
> git clean -d -f -x                                                                                                                                             
Removing zig-cache/
> zig build -Doptimize=ReleaseSafe                                                                                                                               
/home/tim/src/zls/build.zig:293:23: error: member function expected 3 argument(s), found 2
        tests_run.argv.insertSlice(0, args) catch @panic("OOM");
        ~~~~~~~~~~~~~~^~~~~~~~~~~~
/usr/local/lib/zig/std/array_list.zig:781:13: note: function declared here
        pub fn insertSlice(
        ~~~~^~
referenced by:
    runBuild__anon_8768: /usr/local/lib/zig/std/Build.zig:2079:37
    main: /usr/local/lib/zig/compiler/build_runner.zig:300:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
/home/tim/.cache/zig/p/12200d71e4b7029ea56a429e24260c6c0e85a3069b0d4ba85eace21a0fd75910aa64/build.zig:5:33: error: no field named 'path' in union 'Build.LazyPath'
        .root_source_file = .{ .path = "DiffMatchPatch.zig" },
                                ^~~~
/usr/local/lib/zig/std/Build.zig:2133:22: note: union declared here
pub const LazyPath = union(enum) {
                     ^~~~~
/home/tim/.cache/zig/p/12201314cffeb40c5e4e3da166217d2c74628c74486414aaf97422bcd2279915b9fd/build.zig:5:33: error: no field named 'path' in union 'Build.LazyPath'
        .root_source_file = .{ .path = "known-folders.zig" },
                                ^~~~
/usr/local/lib/zig/std/Build.zig:2133:22: note: union declared here
pub const LazyPath = union(enum) {
                     ^~~~~
```

**Comment by Techatrix** [comment]
Response to your previous comment:

This is something that kind of exists right now. I wrote a proof of concept [select-zls-version.zig](https://gist.github.com/Techatrix/02ce258460d4ca1c8424e600458575b0) script that takes a Zig version and outputs a compatible ZLS version. It uses the minimum Zig version and the Zig version with which ZLS's CI has built the binaries to resolve what the latest compatible version is. Checking every Zig version with every ZLS version is a bit extreme. There are thousands of Zig and ZLS versions. The matrix would have millions of cells.

I am currently working trying to improve on this concept and provide a API endpoint so that tools that take care of installing Zig and ZLS can query which ZLS binary to get. 

Unfortunately this won't help you because you are compiling from source and CI can't validate version that have no upstream binary.

**Comment by Techatrix** [comment]
> I still get the same error originally reported when cleanly rebuilding zls:

What output do you get when you run `zig env`?

**Comment by timblaktu** [comment]
```
 [2]tim@sector17g-debian:~/src/zls
> zig env                                                                                                                                                        zls (master) % (⎈|BINARY-N/A:N/A)
{
 "zig_exe": "/usr/local/bin/zig",
 "lib_dir": "/usr/local/lib/zig",
 "std_dir": "/usr/local/lib/zig/std",
 "global_cache_dir": "/home/tim/.cache/zig",
 "version": "0.13.0-dev.75+5c9eb4081",
 "target": "x86_64-linux.4.19...6.5.7-gnu.2.36",
 "env": {
  "ZIG_GLOBAL_CACHE_DIR": null,
  "ZIG_LOCAL_CACHE_DIR": null,
  "ZIG_LIB_DIR": null,
  "ZIG_LIBC": null,
  "ZIG_BUILD_RUNNER": null,
  "ZIG_VERBOSE_LINK": null,
  "ZIG_VERBOSE_CC": null,
  "ZIG_BTRFS_WORKAROUND": null,
  "ZIG_DEBUG_CMD": null,
  "CC": null,
  "NO_COLOR": null,
  "XDG_CACHE_HOME": null,
  "HOME": "/home/tim"
 }
}
```

Thanks for that info re: the zig select script. 

Coming full-circle, I don't actually _need_ to compile zls from source, what I _need_ is to _use_ zls in neovim. I figured I'd start with compiling from source, bc I'm currently using Debian and [the README](https://github.com/zigtools/zls#from-source) says it's very easy and you need to do it with zig built from master, but I digress..

I will probably now just revert my installed zig to latest stable and then see what my neovim installs for me via lsp/mason..

**Comment by timblaktu** [comment]
ok, scratch that, I won't be using mason to install ZLS, bc I found [this warning in your wiki](https://github.com/zigtools/zls/wiki/Installation#neovim--vim8). So, I guess the best practice for users to to just fetch the versioned pair of zig,zls binaries, right?

**Comment by Techatrix** [comment]
Based on what I could identify from the line numbers. You are using Zig `0.13.0-dev.75+5c9eb4081` but the content of `/usr/local/lib/zig` is from the time of 5c9eb408167672f1389c6fe58bb7851be80204de but after the breaking change occured. When you compiled  `0.13.0-dev.75+5c9eb4081` from source, somehow your Zig standard library did not get updated.

The warning you mentioned is about using Mason to install ZLS while using a master/development built of Zig. Using Zig 0.12.0 and ZLS 0.12.0 (through Mason) is totally ok. Sticking to tagged releases is generally recommended to newcomers anyway.
