### PR TITLE
Update to Zig std's new AST format

### LINKED ISSUE #150: zls errors out with "index out of bounds" while using it with VS code
zls was working correctly and started throwing with the following error logs.

(as far as I remember, this started happening when I started writing `///` comments in the source code - just putting it out there to give more context)

I can share the source code/project if needed for debugging.

```
[Info  - 12:43:43 am] [info-main] Found zig in PATH: /home/scriptnull/s/zig

[Info  - 12:43:43 am] [info-main] Using zig executable /home/scriptnull/s/zig

[debug-main] Got workspace folders in initialization.

[debug-main] Loaded folder file:///home/scriptnull/recurse

[Info  - 12:43:43 am] [info-main] ClientCapabilities{ .supports_snippets = true, .supports_semantic_tokens = true, .hover_supports_md = true, .completion_doc_supports_md = true, .supports_workspace_folders = true }

[debug-main] Took 0ms to process method initialize

[debug-main] Took 0ms to process method initialized

[debug-doc_store] Opened document: file:///home/scriptnull/recurse/tarmarind/lib/src/main.zig

[debug-doc_store] Opened document: file:///home/scriptnull/recurse/tarmarind/lib/build.zig

[debug-doc_store] Document is a build file, extracting packages...

[debug-doc_store] Failed to load packages of build file file:///home/scriptnull/recurse/tarmarind/lib/build.zig (error: error.AccessDenied)

[debug-doc_store] Opened document: file:///home/scriptnull/s/zig/lib/zig/std/std.zig

[debug-doc_store] Opened document: file:///home/scriptnull/s/zig/lib/zig/std/fs.zig

[debug-doc_store] Opened document: file:///home/scriptnull/s/zig/lib/zig/std/fs/file.zig

[debug-doc_store] Opened document: file:///home/scriptnull/s/zig/lib/zig/std/os.zig

[debug-doc_store] Opened document: file:///home/scriptnull/s/zig/lib/zig/std/testing.zig

[debug-main] Took 90ms to process method textDocument/didOpen

[debug-main] Took 1ms to process method textDocument/documentSymbol

[debug-doc_store] New text for document file:///home/scriptnull/recurse/tarmarind/lib/src/main.zig

[debug-main] Took 1ms to process method textDocument/didChange

[debug-main] Took 0ms to process method textDocument/completion

[debug-doc_store] New text for document file:///home/scriptnull/recurse/tarmarind/lib/src/main.zig

[debug-main] Took 1ms to process method textDocument/didChange

[debug-main] Took 0ms to process method textDocument/completion

[debug-doc_store] New text for document file:///home/scriptnull/recurse/tarmarind/lib/src/main.zig

[debug-main] Took 1ms to process method textDocument/didChange

index out of bounds
/home/scriptnull/s/zls/src/semantic_tokens.zig:105:57: 0x2fd711 in semantic_tokens.fieldTokenType (zls)
    return @as(?TokenType, switch (handle.tree.token_ids[container_decl.kind_token]) {
                                                        ^
/home/scriptnull/s/zls/src/semantic_tokens.zig:501:35: 0x2f3069 in semantic_tokens.writeNodeTokens (zls)
                    fieldTokenType(container_decl, handle)
                                  ^
/home/scriptnull/s/zls/src/semantic_tokens.zig:274:23: 0x2ec381 in semantic_tokens.writeNodeTokens (zls)
            try await @asyncCall(child_frame, {}, writeNodeTokens, .{ builder, arena, store, var_decl.getTrailer("init_node") });
                      ^
/home/scriptnull/s/zls/src/semantic_tokens.zig:252:31: 0x2eb15a in semantic_tokens.writeNodeTokens (zls)
                    try await @asyncCall(child_frame, {}, writeNodeTokens, .{ builder, arena, store, child });
                              ^
/home/scriptnull/s/zls/src/semantic_tokens.zig:378:23: 0x2ef4f9 in semantic_tokens.writeNodeTokens (zls)
            try await @asyncCall(child_frame, {}, writeNodeTokens, .{ builder, arena, store, fn_proto.getTrailer("body_node") });
                      ^
/home/scriptnull/s/zls/src/semantic_tokens.zig:252:31: 0x2eb15a in semantic_tokens.writeNodeTokens (zls)
                    try await @asyncCall(child_frame, {}, writeNodeTokens, .{ builder, arena, store, child });
                              ^
/home/scriptnull/s/zls/src/semantic_tokens.zig:739:24: 0x2a47d0 in semantic_tokens.writeAllSemanticTokens (zls)
    try writeNodeTokens(&builder, arena, store, &handle.tree.root_node.base);
                       ^
/home/scriptnull/s/zls/src/main.zig:1178:71: 0x28fe5d in semanticTokensHandler (zls)
        const token_array = try semantic_tokens.writeAllSemanticTokens(arena, &document_store, handle, offset_encoding);
                                                                      ^
/home/scriptnull/s/zls/src/main.zig:1454:53: 0x27e89c in processJsonRpc (zls)
                    done = extractErr(method_info[2](arena, id, request_obj, config));
                                                    ^
/home/scriptnull/s/zls/src/main.zig:1651:27: 0x273251 in main (zls)
        try processJsonRpc(&arena, &json_parser, buf, config);
                          ^
/home/scriptnull/s/zig/lib/zig/std/start.zig:252:37: 0x245cfd in std.start.posixCallMainAndExit (zls)
            const result = root.main() catch |err| {
                                    ^
/home/scriptnull/s/zig/lib/zig/std/start.zig:123:5: 0x245a3f in std.start._start (zls)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
[Error - 12:43:44 am] Connection to server got closed. Server will not be restarted.
[Error - 12:43:44 am] Request textDocument/semanticTokens failed.
Error: Connection got disposed.
	at Object.dispose (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/main.js:967:25)
	at Object.dispose (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-languageclient/lib/client.js:2320:42)
	at LanguageClient.handleConnectionClosed (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-languageclient/lib/client.js:2307:18)
	at CallbackList.invoke (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/events.js:125:36)
	at closeHandler (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/main.js:288:26)
	at CallbackList.invoke (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/events.js:125:36)
	at StreamMessageWriter.fireClose (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/messageWriter.js:39:27)
	at Socket.<anonymous> (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/messageWriter.js:58:46)
	at Socket.emit (events.js:203:13)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 12:43:44 am] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/main.js:967:25)
	at Object.dispose (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-languageclient/lib/client.js:2320:42)
	at LanguageClient.handleConnectionClosed (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-languageclient/lib/client.js:2307:18)
	at CallbackList.invoke (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/events.js:125:36)
	at closeHandler (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/main.js:288:26)
	at CallbackList.invoke (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/events.js:125:36)
	at StreamMessageWriter.fireClose (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/messageWriter.js:39:27)
	at Socket.<anonymous> (/home/scriptnull/.vscode/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/messageWriter.js:58:46)
	at Socket.emit (events.js:203:13)
	at Pipe.<anonymous> (net.js:588:12)
```

### LINKED ISSUE #152: zls crashes on VSCode when struct fields with align specified
test file:
```zig
const T = struct { x: bool align(4) = 0 };
```
output:
```
integer overflow
C:\Projects\zls\src\offsets.zig:84:28: 0x7ff73e4973d1 in offsets.tokenRelativeLocation (zls.obj)
    while (i < token_start - start_index) {
                           ^
C:\Projects\zls\src\semantic_tokens.zig:63:56: 0x7ff73e4d64ee in semantic_tokens.Builder::semantic_tokens.Builder.add (zls.obj)
        const delta_loc = offsets.tokenRelativeLocation(self.handle.tree, start_idx, token, self.encoding) catch return;
                                                       ^
C:\Projects\zls\src\semantic_tokens.zig:220:23: 0x7ff73e47f0b0 in semantic_tokens.writeContainerField (zls.obj)
        try writeToken(builder, eq_tok, .operator);
                      ^
C:\Projects\zls\src\semantic_tokens.zig:307:44: 0x7ff73e46fb71 in semantic_tokens.writeNodeTokens (zls.obj)
                    try writeContainerField(builder, arena, store, container_field, field_token_type, child_frame);
                                           ^
C:\Projects\zls\src\semantic_tokens.zig:274:23: 0x7ff73e46edf9 in semantic_tokens.writeNodeTokens (zls.obj)
            try await @asyncCall(child_frame, {}, writeNodeTokens, .{ builder, arena, store, var_decl.getTrailer("init_node") });
                      ^
C:\Projects\zls\src\semantic_tokens.zig:252:31: 0x7ff73e46dba4 in semantic_tokens.writeNodeTokens (zls.obj)
                    try await @asyncCall(child_frame, {}, writeNodeTokens, .{ builder, arena, store, child });
                              ^
C:\Projects\zls\src\semantic_tokens.zig:739:24: 0x7ff73e41f3c1 in semantic_tokens.writeAllSemanticTokens (zls.obj)
    try writeNodeTokens(&builder, arena, store, &handle.tree.root_node.base);
                       ^
C:\Projects\zls\src\main.zig:1178:71: 0x7ff73e40cf1e in semanticTokensHandler (zls.obj)
        const token_array = try semantic_tokens.writeAllSemanticTokens(arena, &document_store, handle, offset_encoding);
                                                                      ^
C:\Projects\zls\src\main.zig:1143:30: 0x7ff73e40bd40 in openDocumentHandler (zls.obj)
    try semanticTokensHandler(arena, id, .{ .params = .{ .textDocument = .{ .uri = req.params.textDocument.uri } } }, config);
                             ^
C:\Projects\zls\src\main.zig:1454:53: 0x7ff73e3f36a5 in processJsonRpc (zls.obj)
                    done = extractErr(method_info[2](arena, id, request_obj, config));
                                                    ^
C:\Projects\zls\src\main.zig:1651:27: 0x7ff73e3d5f5f in main (zls.obj)
        try processJsonRpc(&arena, &json_parser, buf, config);
                          ^
C:\Projects\zig\lib\std\start.zig:134:65: 0x7ff73e3d1f1e in std.start.WinMainCRTStartup (zls.obj)
        _ = @import("start_windows_tls.zig");
                                                                ^
Unable to dump stack trace: FileNotFound
```

### LINKED ISSUE #153: Crashes on writing `callconv(.Stdcall)` in a function definition.
This happened while I was adding the WINAPI function
```rs
pub extern "kernel32" fn SetConsoleMode(hConsoleHandle: windows.HANDLE, dwMode: windows.DWORD) callconv(.Stdcall) windows.BOOL;
```
To my code, and I was just beginning to write .Stdcall, before I had written any function parameters or the return type.

ZLS was being used with VSCode, and the editor told me ZLS has crashed 3+ times within the same minute.

### LINKED ISSUE #157: crash on `const a = a;`
as title, easy to repro

### LINKED ISSUE #237: heads up: major breakage planned
This will be merged soon: https://github.com/ziglang/zig/pull/7920

I think this will cause a lot of work to update ZLS to be working again. Sorry about that. The consolation prize is that once again the perf of parsing zig code is significantly improved (check out some of the benchmarks in that thread).

### LINKED ISSUE #242: container 'std.zig.ast.Node' has no member called 'Use'
When running zig build -Drelease-safe, I get this error. I think it might be related to #238?

Here is my trace:
```
~\A\R\zls>zig build -Drelease-safe
.\src\analysis.zig:2039:28: error: container 'std.zig.ast.Node' has no member called 'Use'
    uses: []const *ast.Node.Use,
                           ^
.\src\analysis.zig:1986:5: note: while checking this field
    scopes: []Scope,
    ^
.\src\document_store.zig:26:5: note: while checking this field
    document_scope: analysis.DocumentScope,
    ^
C:\Users\**\AppData\Roaming\ziglang\lib\zig\std\hash_map.zig:293:13: note: while checking this field
            value: V,
            ^
C:\Users\**\AppData\Roaming\ziglang\lib\zig\std\hash_map.zig:357:40: note: referenced here
            pub fn next(it: *Iterator) ?*Entry {
                                       ^
.\src\document_store.zig:614:26: note: referenced here
    while (entry_iterator.next()) |entry| {
                         ^
.\src\analysis.zig:1540:34: error: container 'std.zig.ast.FnProto' has no member called 'ParamDecl'
    param_decl: *ast.Node.FnProto.ParamDecl,
                                 ^
~\A\R\zls[1]>zig version
0.8.0-dev.1427+0447a2c04
```

OS: Windows 10

### LINKED ISSUE #244: problem compiling latest build with 0.7.1 and 0.8.0 (latest build)
I this message when I tried compiling zls with both 0.7.1 and 0.8.0

> .\src\document_store.zig:110:36: error: no member named 'shrinkAndFree' in struct 'std.array_list.ArrayListAlignedUnmanaged(document_store.Pkg,null)'
                build_file.packages.shrinkAndFree(allocator, 0);
                                   ^
.\src\document_store.zig:419:12: note: referenced here
        }) catch |err| {
           ^
.\src\main.zig:1193:5: note: referenced here
    try document_store.applySave(handle);
    ^
.\src\semantic_tokens.zig:95:12: error: enum 'std.builtin.CallingConvention' has no field named 'Inline'
) callconv(.Inline) !void {
           ^
C:\zig\lib\std\builtin.zig:153:31: note: 'std.builtin.CallingConvention' declared here
pub const CallingConvention = enum {
                              ^
.\src\semantic_tokens.zig:270:21: note: referenced here
                try writeToken(builder, block_node.label, .label);
                    ^
.\src\analysis.zig:202:26: error: expected optional type, found '*std.zig.ast.Node'
            return ((decl.name orelse return null).castTag(.StringLiteral) orelse return null).token;
                         ^
.\src\analysis.zig:202:32: note: referenced here
            return ((decl.name orelse return null).castTag(.StringLiteral) orelse return null).token;
                               ^
zls...The following command exited with error code 1:
C:\zig\zig.exe build-exe C:\zls2\src\main.zig --pkg-begin build_options C:\zls2\zig-cache\zls_build_options.zig --pkg-end -OReleaseSafe --cache-dir C:\zls2\zig-cache --global-cache-dir C:\Users\hgsba\AppData\Local\zig --name zls --pkg-begin known-folders C:\zls2\src\known-folders\known-folders.zig --pkg-end --enable-cache
error: the following build command failed with exit code 1:
C:\zls2\zig-cache\o\5a46f03cc1826362517cf7152e75e559\build.exe C:\zig\zig.exe C:\zls2 C:\zls2\zig-cache C:\Users\hgsba\AppData\Local\zig -Drelease-safe

### PR DESCRIPTION
**Pull request by Luukdegram**
Started updating zls to use the new AST that was introduced in https://github.com/ziglang/zig/pull/7920
I hope to get this finished quickly so people can update to the latest master again.
Perhaps we should consider creating a new binary release after this as well.

Will fix : 
- fixes #237 
- fixes #152
- fixes #157
- fixes #153
- fixes #150
- fixes #242
- fixes #244

This also introduces a new option to `zls.json`, allowing the server to skip finding for references in std. 
This means that when searching for references of a user's function, it will skip searching through std to find a reference to it, allowing for a big speedup in lookups. This is only for references. Go to definition and renaming will continue to work as is.
The option can be enabled by setting the following field to `true`:
`skip_std_references`

TODO's:
- [x] Implement errors (completions/docs/etc)
- [x] Semantic tokens (currently commented out)
- [x] makeScopeInternal
- [x] resolveTypeOfNodeInternal
- [x] usingnamespace
- [x] Implement `test ""{}` support
- [x] Make it actually compile
- [x] Ensure no more `@TODO:` inserted by me are left
- [x] Goto definition on imports.
- [x] Completion for generic types that are imported.
- [x] Completion for `Try`
- [x] Incorrect completions. i.e. https://github.com/vrischmann/zig-sqlite/blob/master/sqlite.zig#L302
- [x] Slice/Array payload completion
- [x] Unwrapping optional in `if` causes crash

### CODE REVIEW

**Comment by Luukdegram** [comment]
To whoever is reading this issue. Any help with finding regressions is very much appreciated.

**Comment by vrischmann** [comment]
I'm currently testing on my project.
I'm getting wrong completions [in this file](https://github.com/vrischmann/zig-sqlite/blob/master/sqlite.zig#L302) for example, zls assumes the type is `std.fmt.FormatOptions` instead of `InitOptions`.

**Comment by Luukdegram** [comment]
> I'm currently testing on my project.
> I'm getting wrong completions [in this file](https://github.com/vrischmann/zig-sqlite/blob/master/sqlite.zig#L302) for example, zls assumes the type is `std.fmt.FormatOptions` instead of `InitOptions`.

Thanks! Added to the TODO list

**Comment by leecannon** [comment]
It looks like `usingnamespace` is not working 100% correctly.

```zig
const namespace = struct {
    pub usingnamespace @import("std");
};

pub fn main() void {
    const a: namespace.mem.Allocator = undefined;
}
```
In this code when typing `namespace.` no completion list is shown for `std` but upon entering `namespace.mem.` the correct completion list for `std.mem` is shown.

With just this: `const a: namespace.mem` mouse over of mem correctly shows `pub const mem = @import("mem.zig");` from `std.zig` and ctrl-click on `mem` correctly results in opening `std.zig`, so it looks like only the completion list is not functioning correcly.

**Comment by Luukdegram** [comment]
> It looks like `usingnamespace` is not working 100% correctly.
> 
> ```zig
> const namespace = struct {
>     pub usingnamespace @import("std");
> };
> 
> pub fn main() void {
>     const a: namespace.mem.Allocator = undefined;
> }
> ```

Thanks for this! I fixed it in the last commit, as well as similar cases to this.

**Comment by leecannon** [comment]
With the latest commit (85937d48ca083d3a422512ac232fbfd7237b58c7) im still not getting completion on `namespace.` with this code:
 ```zig
 const namespace = struct {
     pub usingnamespace @import("std");
 };
 
 pub fn main() void {
     const a: namespace.mem.Allocator = undefined;
 }
 ```

**Comment by Luukdegram** [comment]
> With the latest commit ([85937d4](https://github.com/zigtools/zls/commit/85937d48ca083d3a422512ac232fbfd7237b58c7)) im still not getting completion on `namespace.` with this code:

My bad, I misunderstood you and thought you ment the completion after typing `a.`
I will try to fix this and come back to you once done.

**Comment by Luukdegram** [comment]
@leecannon It should now be working correctly.

**Comment by leecannon** [comment]
Looks like that fixed that case but here is slight more complex one.

Sorry about this one, i've tried but failed to get a single file reproduction. It seems replicating the same hierarchy of structs in one file does not have the same issue (single file code at the bottom, it does not have any of the issues the muti-file version has).

In the main file the `usingnamespace` correctly results in `std` being available in completion list when typing `s` but `SomeStruct` and `SomeStruct.Number` are not.
But `g.SomeStruct` is in the completion list when typing `g.`

Also hover and ctrl-click work for the one prefixed with `g.` but not the `usingnamespace` ones.

So sorry about this, but all of my libs essentially have this structure (a lib.zig file for exporting as the pakage root and a global.zig file that every internal file has a `usingnamespace` of)

#### main.zig
```zig
usingnamespace @import("globals.zig");
const g = @import("globals.zig");

pub fn main() void {
    std.log.info("{}", .{SomeStruct.Number});
    std.log.info("{}", .{g.SomeStruct.Number});
}
```
#### globals.zig
```zig
pub const std = @import("std");
pub usingnamespace @import("lib.zig");
```
#### lib.zig
```zig
pub usingnamespace @import("structs.zig");
```
#### structs.zig
```zig
usingnamespace @import("globals.zig");

pub const SomeStruct = struct {
    pub const Number = 12;
};
```
### Single file version (no issues)
```zig
usingnamespace globals;
const g = globals;

pub fn main() void {
    std.log.info("{}", .{SomeStruct.Number});
    std.log.info("{}", .{g.SomeStruct.Number});
}

const globals = struct {
    pub const std = @import("std");
    pub usingnamespace lib;
};

const lib = struct {
    pub usingnamespace structs;
};

const structs = struct {
    usingnamespace globals;

    pub const SomeStruct = struct {
        pub const Number = 12;
    };
};
```

**Comment by Luukdegram** [comment]
Thanks for the detailed case and more importantly, thank you for testing this branch. I'll try to fix this tomorrow and keep you updated.

**Comment by alexnask** [comment]
Thank you so much for this!

**Comment by Luukdegram** [comment]
@leecannon I pushed a fix for your namespaces use case. Would you mind testing this in your existing projects and see if it works as expected?

**Comment by leecannon** [comment]
Looks all good to me!

**Comment by SuperAuguste** [comment]
Thanks so much for maintaining ZLS Luuk! I pulled this PR and everything looks good except for a very minor bug that can be recreated like this:
```zig
const std = @import("std");

pub fn main() anyerror!void {
    std.ArrayList. // <-- if you ask for completions here, it'll list ArrayList as a possibility despite it being invalid
}
```

This behavior seems to occur for any function where a completion is requested.

**Comment by Luukdegram** [comment]
@SuperAuguste Thanks for the findings. It seems it was happening with the original zls as well. Fixed it regardless, so should be fine now.

**Comment by SuperAuguste** [comment]
This looks good, merging! Thanks!
