### PR TITLE
build_runner: Require some paths to be given

### LINKED ISSUE #367: File size/LOC limit?
Hi,

I'm curious about knowing if zls has a max file size it can analyze, I'm trying to use zls with zig-vulkan, zls is not working (as in not giving any suggestions coming from that library), the main zig file has ~23.9k LOC

### PR DESCRIPTION
**Pull request by maringuu**
For the build runner we now require the following to ge given in the cli args:
- zig_exe
- build_root
- cache_root
- global_cache_root

This fixes the path for packages that use one or more from the above to place
their files.

Some examples are `vulkan-zig` and `zig-wayland` that both place their files in the `zig-cache` directory.

For symmetry with the original `build_runner.zig` I just copied over the code from it. We don't actually need `global_cache_root` so we might consider removing it.

Probably closes #367

### CODE REVIEW

**Comment by maringuu** [comment]
@InfRandomness Can you test if this fixes your problem?
For me zig-vulkan works on the zig-0.8.0 branch but I didn't test master.

**Comment by InfRandomness** [comment]
> @InfRandomness Can you test if this fixes your problem?
> For me zig-vulkan works on the zig-0.8.0 branch but I didn't test master.

I had the problem with zig 0.9.0-dev, I will check it out a bit later

**Comment by InfRandomness** [comment]
For some reason, it does not compile with zig master :
```
./src/setup.zig:228:31: error: expected type 'type', found '[]u8'
    var it = std.mem.tokenize(env_path, &[_]u8{std.fs.path.delimiter});
                              ^
./src/setup.zig:68:24: note: referenced here
    var zig_exe_path = try findZig(allocator);
                       ^
./src/main.zig:1805:13: note: referenced here
            try setup.wizard(allocator);
            ^
./src/known-folders/known-folders.zig:149:38: error: expected type 'type', found '*[8192]u8'
        var line_it = std.mem.split(&read, "\n");
                                     ^
zls...The following command exited with error code 1:
/home/build/zig/build/zig build-exe /home/build/zls2/src/main.zig --pkg-begin build_options /home/build/zls2/zig-cache/zls_build_options.zig --pkg-end --cache-dir /home/build/zls2/zig-cache --global-cache-dir /home/build/.cache/zig --name zls --pkg-begin known-folders /home/build/zls2/src/known-folders/known-folders.zig --pkg-end --enable-cache
error: the following build command failed with exit code 1:
/home/build/zls2/zig-cache/o/6e3839e6ed1bb532f8b86eff3a97d46b/build /home/build/zig/build/zig /home/build/zls2 /home/build/zls2/zig-cache /home/build/.cache/zig
```

**Comment by InfRandomness** [comment]
https://github.com/zigtools/zls/issues/372#issuecomment-895340244

**Comment by InfRandomness** [comment]
Would it be possible if you updated your branch with the latest upstream changes on master ? so I can build this

**Comment by maringuu** [comment]
I'll rebase on zls master once I'm back from vacation.
The rebase should be trivial, so I guess you can do it yourself meanwhile.

**Comment by maringuu** [comment]
Rebased.

**Comment by maringuu** [comment]
@SuperAuguste Gentle ping :)

**Comment by SuperAuguste** [comment]
Oops sorry, will merge once ci passes:)

**Comment by SuperAuguste** [comment]
LGTM!
