### ISSUE TITLE
zls compiling version checking doesnt identify 0.15.0 being further than 0.15.0-dev

### ISSUE THREAD

**Issue by MahdiGMK** [zigtools/zls#2454]
### Zig Version

0.15.0

### ZLS Version

3ed95ecd5f41bb98c3c7027f80664404ed001771

### Steps to Reproduce and Observed Behavior

try to compile it with the new zig 0.15.0 stable
```
anyzig: zig '0.15.0' already exists at '/home/mahdigmk/.cache/zig/p/N-V-__8AACFNhBSaulceFT2Wx6Mx-ycGtZh7CEztyVdtX2jW'
build.zig:725:9: error: Your Zig version does not meet the minimum build requirement:
                          required Zig version: 0.15.0-dev.1526+b8124d9c0 (or greater)
                          actual   Zig version: 0.15.0

                        Please download or compile a tagged release of ZLS.
                          -> https://github.com/zigtools/zls/releases
                          -> https://github.com/zigtools/zls/releases/tag/0.15.0 (may not exist yet)
        @compileError(message);
```

### Expected Behavior

as you can see I'm using zig0.15.0 yet it still throws this error

### Log Output

```shell

```

**Comment by nhanb** [comment]
Same problem on 0.15.1:

```
$ zig build -Doptimize=ReleaseSafe
build.zig:725:9: error: Your Zig version does not meet the minimum build requirement:
                          required Zig version: 0.15.0-dev.1526+b8124d9c0 (or greater)
                          actual   Zig version: 0.15.1
                        
                        Please download or compile a tagged release of ZLS.
                          -> https://github.com/zigtools/zls/releases
                          -> https://github.com/zigtools/zls/releases/tag/0.15.1 (may not exist yet)
```

**Comment by donpdonp** [comment]
its been fixed with https://github.com/zigtools/zls/commit/c156c6c402fd03525c3d093151b50b9233f190ee I just tried it with 0.15.1 and zig build completes without error.

**Comment by techatrix** [comment]
ZLS 0.15.0 has been released which works with Zig 0.15.1.

**Comment by nektro** [comment]
what was the root cause here, will this happen again when 0.16.0 releases?

**Comment by techatrix** [comment]
This is an intentional restriction. A 0.15.x tagged release of Zig should not be used with a 0.15.0-dev development build of ZLS until it's been explicitly updated to support the given tagged release.
