### ISSUE TITLE
`zls` fails to build with Zig `0.17.0-dev.56+a8226cd53` due to removed `std.zig.BuiltinFn.Tag` enum members

### ISSUE THREAD

**Issue by 1337est** [zigtools/zls#3180]
### Zig Version

0.17.0-dev.56+a8226cd53

### ZLS Version

0.17.0-dev.1+295cedd8

### Client / Code Editor / Extensions

nvim 0.12.0

### Steps to Reproduce and Observed Behavior

1. Install the latest zig version `0.17.0-dev.56+a8226cd53`.
2. Try and build `zls` via `zig build -Doptimize=ReleaseSafe`.
3. Error message from zig compiler:

```
install
└─ install zls
   └─ compile exe zls ReleaseSafe native 2 errors
src/analysis.zig:2408:18: error: enum 'zig.BuiltinFn.Tag' has no member named 'c_import'
                .c_import => {
                ~^~~~~~~~
/home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/zig/BuiltinFn.zig:1:17: note: enum declared here
pub const Tag = enum {
                ^~~~
referenced by:
    resolveBindingOfNodeUncached: src/analysis.zig:3156:59
    resolveBindingOfNodeInternal: src/analysis.zig:1972:62
    14 reference(s) hidden; use '-freference-trace=16' to see all references
src/features/inlay_hints.zig:41:6: error: no field named 'c_define' in struct 'enums.EnumFieldStruct(zig.BuiltinFn.Tag,bool,null)'
    .c_define = true,
     ^~~~~~~~
/home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/enums.zig:37:12: note: struct declared here
    return @Struct(.auto, null, std.meta.fieldNames(E), &@splat(Data), &@splat(.{ .default_value_ptr = default_ptr }));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: 2 compilation errors
failed command: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/bin/zig build-exe -OReleaseSafe --dep exe_options --dep known-folders --dep tracy --dep zls -Mroot=/home/adrian/.dev/pkg/zig_lang/zls/src/main.zig -Mexe_options=.zig-cache/c/0fb60a166fb299ad8a8e2fac2bf46047/options.zig -OReleaseSafe -Mknown-folders=/home/adrian/.dev/pkg/zig_lang/zls/zig-pkg/known_folders-0.0.0-Fy-PJk3KAACzUg2us_0JvQQmod1ZA8jBt7MuoKCihq88/known-folders.zig -fno-sanitize-c -OReleaseSafe --dep options -Mtracy=/home/adrian/.dev/pkg/zig_lang/zls/src/tracy.zig -OReleaseSafe --dep diffz --dep lsp --dep tracy --dep build_options --dep version_data -Mzls=/home/adrian/.dev/pkg/zig_lang/zls/src/zls.zig -Moptions=.zig-cache/c/9c752c5b2da741d3da46ec4179cea1bc/options.zig -OReleaseSafe -Mdiffz=/home/adrian/.dev/pkg/zig_lang/zls/zig-pkg/diffz-0.0.1-G2tlISzNAQCldmOcINavGmF1zdt20NFPXeM8d07jp_68/DiffMatchPatch.zig -OReleaseSafe --dep parser --dep types -Mlsp=/home/adrian/.dev/pkg/zig_lang/zls/zig-pkg/lsp_kit-0.1.0-bi_PL3IyDACfp1xdTnkiOHEok2YpPCCCJHuuOcNzjl1D/src/lsp.zig -Mbuild_options=.zig-cache/c/a57edc9e1fe8e8a5896260e52fbb5c2f/options.zig -Mversion_data=.zig-cache/o/d9e47b0f14ca412de429ec6a70739174/version_data.zig -OReleaseSafe -Mparser=/home/adrian/.dev/pkg/zig_lang/zls/zig-pkg/lsp_kit-0.1.0-bi_PL3IyDACfp1xdTnkiOHEok2YpPCCCJHuuOcNzjl1D/src/parser.zig -OReleaseSafe --dep parser -Mtypes=.zig-cache/o/ba94fe4a48795fb620db3acbc2eb30e9/lsp_types.zig --cache-dir .zig-cache --global-cache-dir /home/adrian/.cache/zig --name zls --zig-lib-dir /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/ --listen=-

Build Summary: 7/10 steps succeeded (1 failed)
install transitive failure
└─ install zls transitive failure
   └─ compile exe zls ReleaseSafe native 2 errors

error: the following build command failed with exit code 1:
.zig-cache/o/92cdbcf6e6755e3d064182ea08fb6f16/build /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/bin/zig /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig /home/adrian/.dev/pkg/zig_lang/zls .zig-cache /home/adrian/.cache/zig --seed 0xc683fd18 -Z3d2514111a80bc9f -Doptimize=ReleaseSafe
```

4. Local fix to remove `c_import`, `c_define`, `c_include`, and `c_undef`. Here is the local patch I made with a working `zig build -Doptimize=ReleaseSafe`:

```
diff --git a/src/analysis.zig b/src/analysis.zig
index 1c3d9535..203d4676 100644
--- a/src/analysis.zig
+++ b/src/analysis.zig
@@ -2405,17 +2405,6 @@ fn resolveTypeOfNodeUncached(analyser: *Analyser, options: ResolveOptions) Error
                     if (try analyser.resolveImportString(analyser.root_handle orelse return null, import_string)) |ty| return ty;
                     return null;
                 },
-                .c_import => {
-                    if (!DocumentStore.supports_build_system) return null;
-                    const cimport_uri = (try analyser.store.resolveCImport(handle, node)) orelse return null;
-
-                    const new_handle = try analyser.store.getOrLoadHandle(cimport_uri) orelse return null;
-
-                    return .{
-                        .data = .{ .container = .root(new_handle) },
-                        .is_type_val = true,
-                    };
-                },
                 .FieldType => {
                     if (params.len < 2) return null;
 
diff --git a/src/features/inlay_hints.zig b/src/features/inlay_hints.zig
index 9ffef22b..02bc4c2f 100644
--- a/src/features/inlay_hints.zig
+++ b/src/features/inlay_hints.zig
@@ -38,9 +38,6 @@ const excluded_builtins_set: std.EnumArray(std.zig.BuiltinFn.Tag, bool) = .init(
     .bit_reverse = true,
     .offset_of = false,
     .call = false,
-    .c_define = true,
-    .c_import = true,
-    .c_include = true,
     .clz = true,
     .cmpxchg_strong = false,
     .cmpxchg_weak = false,
@@ -48,7 +45,6 @@ const excluded_builtins_set: std.EnumArray(std.zig.BuiltinFn.Tag, bool) = .init(
     .compile_log = true, // variadic
     .const_cast = true,
     .ctz = true,
-    .c_undef = true,
     .c_va_arg = false,
     .c_va_copy = false,
     .c_va_end = false,
diff --git a/tests/lsp_features/hover.zig b/tests/lsp_features/hover.zig
index c2ea10cc..385228c5 100644
--- a/tests/lsp_features/hover.zig
+++ b/tests/lsp_features/hover.zig
@@ -590,44 +590,44 @@ test "enum" {
     );
 }
 
-test "union" {
-    try testHover(
-        \\const Comptime<cursor>Reason = union(enum) {
-        \\  c_import: struct {
-        \\      block: *Block,
-        \\      src: LazySrcLoc,
-        \\  },
-        \\  comptime_ret_ty: struct {
-        \\      block: *Block,
-        \\      func: Air.Inst.Ref,
-        \\      func_src: LazySrcLoc,
-        \\      return_ty: Type,
-        \\  },
-        \\
-        \\  fn explain(cr: ComptimeReason, sema: *Sema, msg: ?*Module.ErrorMsg) !void {
-        \\      // many lines here
-        \\  }
-        \\};
-    ,
-        \\```zig
-        \\const ComptimeReason = union(enum) {
-        \\  c_import: struct {
-        \\      block: *Block,
-        \\      src: LazySrcLoc,
-        \\  },
-        \\  comptime_ret_ty: struct {
-        \\      block: *Block,
-        \\      func: Air.Inst.Ref,
-        \\      func_src: LazySrcLoc,
-        \\      return_ty: Type,
-        \\  },
-        \\}
-        \\```
-        \\```zig
-        \\(type)
-        \\```
-    );
-}
+// test "union" {
+//     try testHover(
+//         \\const Comptime<cursor>Reason = union(enum) {
+//         \\  c_import: struct {
+//         \\      block: *Block,
+//         \\      src: LazySrcLoc,
+//         \\  },
+//         \\  comptime_ret_ty: struct {
+//         \\      block: *Block,
+//         \\      func: Air.Inst.Ref,
+//         \\      func_src: LazySrcLoc,
+//         \\      return_ty: Type,
+//         \\  },
+//         \\
+//         \\  fn explain(cr: ComptimeReason, sema: *Sema, msg: ?*Module.ErrorMsg) !void {
+//         \\      // many lines here
+//         \\  }
+//         \\};
+//     ,
+//         \\```zig
+//         \\const ComptimeReason = union(enum) {
+//         \\  c_import: struct {
+//         \\      block: *Block,
+//         \\      src: LazySrcLoc,
+//         \\  },
+//         \\  comptime_ret_ty: struct {
+//         \\      block: *Block,
+//         \\      func: Air.Inst.Ref,
+//         \\      func_src: LazySrcLoc,
+//         \\      return_ty: Type,
+//         \\  },
+//         \\}
+//         \\```
+//         \\```zig
+//         \\(type)
+//         \\```
+//     );
+// }
 
 test "enum member" {
     try testHover(
```

5. It does not pass all tests as there is explicit test coverage for these currently. Here is the output of my `zig build test`:
```
test
└─ test-build-runner
   └─ run build_runner_check (no_root_source_file.zig)
      └─ run build runner (no_root_source_file.zig) failure
src/build_runner/build_runner.zig:286:25: error: no field named 'verbose_cimport' in struct 'Build'
                builder.verbose_cimport = true;
                        ^~~~~~~~~~~~~~~
/home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/Build.zig:1:1: note: struct declared here
const Build = @This();
^~~~~
referenced by:
    callMain [inlined]: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:699:88
    callMainWithArgs [inlined]: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:638:20
    posixCallMainAndExit: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:590:38
    2 reference(s) hidden; use '-freference-trace=5' to see all references
error: process exited with error code 2
failed command: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/bin/zig build --build-file /home/adrian/.dev/pkg/zig_lang/zls/tests/build_runner_cases/no_root_source_file.zig --build-runner /home/adrian/.dev/pkg/zig_lang/zls/src/build_runner/build_runner.zig --cache-dir ./.zig-cache/ --global-cache-dir /home/adrian/.cache/zig/ --zig-lib-dir /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/

test
└─ test-build-runner
   └─ run build_runner_check (module_root_source_file_collision.zig)
      └─ run build runner (module_root_source_file_collision.zig) failure
src/build_runner/build_runner.zig:286:25: error: no field named 'verbose_cimport' in struct 'Build'
                builder.verbose_cimport = true;
                        ^~~~~~~~~~~~~~~
/home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/Build.zig:1:1: note: struct declared here
const Build = @This();
^~~~~
referenced by:
    callMain [inlined]: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:699:88
    callMainWithArgs [inlined]: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:638:20
    posixCallMainAndExit: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:590:38
    2 reference(s) hidden; use '-freference-trace=5' to see all references
error: process exited with error code 2
failed command: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/bin/zig build --build-file /home/adrian/.dev/pkg/zig_lang/zls/tests/build_runner_cases/module_root_source_file_collision.zig --build-runner /home/adrian/.dev/pkg/zig_lang/zls/src/build_runner/build_runner.zig --cache-dir ./.zig-cache/ --global-cache-dir /home/adrian/.cache/zig/ --zig-lib-dir /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/

test
└─ test-build-runner
   └─ run build_runner_check (public_module_with_generated_file.zig)
      └─ run build runner (public_module_with_generated_file.zig) failure
src/build_runner/build_runner.zig:286:25: error: no field named 'verbose_cimport' in struct 'Build'
                builder.verbose_cimport = true;
                        ^~~~~~~~~~~~~~~
/home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/Build.zig:1:1: note: struct declared here
const Build = @This();
^~~~~
referenced by:
    callMain [inlined]: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:699:88
    callMainWithArgs [inlined]: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:638:20
    posixCallMainAndExit: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:590:38
    2 reference(s) hidden; use '-freference-trace=5' to see all references
error: process exited with error code 2
failed command: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/bin/zig build --build-file /home/adrian/.dev/pkg/zig_lang/zls/tests/build_runner_cases/public_module_with_generated_file.zig --build-runner /home/adrian/.dev/pkg/zig_lang/zls/src/build_runner/build_runner.zig --cache-dir ./.zig-cache/ --global-cache-dir /home/adrian/.cache/zig/ --zig-lib-dir /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/

test
└─ test-build-runner
   └─ run build_runner_check (add_module.zig)
      └─ run build runner (add_module.zig) failure
src/build_runner/build_runner.zig:286:25: error: no field named 'verbose_cimport' in struct 'Build'
                builder.verbose_cimport = true;
                        ^~~~~~~~~~~~~~~
/home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/Build.zig:1:1: note: struct declared here
const Build = @This();
^~~~~
referenced by:
    callMain [inlined]: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:699:88
    callMainWithArgs [inlined]: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:638:20
    posixCallMainAndExit: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:590:38
    2 reference(s) hidden; use '-freference-trace=5' to see all references
error: process exited with error code 2
failed command: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/bin/zig build --build-file /home/adrian/.dev/pkg/zig_lang/zls/tests/build_runner_cases/add_module.zig --build-runner /home/adrian/.dev/pkg/zig_lang/zls/src/build_runner/build_runner.zig --cache-dir ./.zig-cache/ --global-cache-dir /home/adrian/.cache/zig/ --zig-lib-dir /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/

test
└─ test-build-runner
   └─ run build_runner_check (empty.zig)
      └─ run build runner (empty.zig) failure
src/build_runner/build_runner.zig:286:25: error: no field named 'verbose_cimport' in struct 'Build'
                builder.verbose_cimport = true;
                        ^~~~~~~~~~~~~~~
/home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/Build.zig:1:1: note: struct declared here
const Build = @This();
^~~~~
referenced by:
    callMain [inlined]: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:699:88
    callMainWithArgs [inlined]: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:638:20
    posixCallMainAndExit: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:590:38
    2 reference(s) hidden; use '-freference-trace=5' to see all references
error: process exited with error code 2
failed command: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/bin/zig build --build-file /home/adrian/.dev/pkg/zig_lang/zls/tests/build_runner_cases/empty.zig --build-runner /home/adrian/.dev/pkg/zig_lang/zls/src/build_runner/build_runner.zig --cache-dir ./.zig-cache/ --global-cache-dir /home/adrian/.cache/zig/ --zig-lib-dir /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/

test
└─ test-build-runner
   └─ run build_runner_check (multiple_module_import_names.zig)
      └─ run build runner (multiple_module_import_names.zig) failure
src/build_runner/build_runner.zig:286:25: error: no field named 'verbose_cimport' in struct 'Build'
                builder.verbose_cimport = true;
                        ^~~~~~~~~~~~~~~
/home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/Build.zig:1:1: note: struct declared here
const Build = @This();
^~~~~
referenced by:
    callMain [inlined]: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:699:88
    callMainWithArgs [inlined]: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:638:20
    posixCallMainAndExit: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:590:38
    2 reference(s) hidden; use '-freference-trace=5' to see all references
error: process exited with error code 2
failed command: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/bin/zig build --build-file /home/adrian/.dev/pkg/zig_lang/zls/tests/build_runner_cases/multiple_module_import_names.zig --build-runner /home/adrian/.dev/pkg/zig_lang/zls/src/build_runner/build_runner.zig --cache-dir ./.zig-cache/ --global-cache-dir /home/adrian/.cache/zig/ --zig-lib-dir /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/

test
└─ test-build-runner
   └─ run build_runner_check (module_self_import.zig)
      └─ run build runner (module_self_import.zig) failure
src/build_runner/build_runner.zig:286:25: error: no field named 'verbose_cimport' in struct 'Build'
                builder.verbose_cimport = true;
                        ^~~~~~~~~~~~~~~
/home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/Build.zig:1:1: note: struct declared here
const Build = @This();
^~~~~
referenced by:
    callMain [inlined]: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:699:88
    callMainWithArgs [inlined]: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:638:20
    posixCallMainAndExit: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:590:38
    2 reference(s) hidden; use '-freference-trace=5' to see all references
error: process exited with error code 2
failed command: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/bin/zig build --build-file /home/adrian/.dev/pkg/zig_lang/zls/tests/build_runner_cases/module_self_import.zig --build-runner /home/adrian/.dev/pkg/zig_lang/zls/src/build_runner/build_runner.zig --cache-dir ./.zig-cache/ --global-cache-dir /home/adrian/.cache/zig/ --zig-lib-dir /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/

test
└─ test-build-runner
   └─ run build_runner_check (define_c_macro.zig)
      └─ run build runner (define_c_macro.zig) failure
src/build_runner/build_runner.zig:286:25: error: no field named 'verbose_cimport' in struct 'Build'
                builder.verbose_cimport = true;
                        ^~~~~~~~~~~~~~~
/home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/Build.zig:1:1: note: struct declared here
const Build = @This();
^~~~~
referenced by:
    callMain [inlined]: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:699:88
    callMainWithArgs [inlined]: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:638:20
    posixCallMainAndExit: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/std/start.zig:590:38
    2 reference(s) hidden; use '-freference-trace=5' to see all references
error: process exited with error code 2
failed command: /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/bin/zig build --build-file /home/adrian/.dev/pkg/zig_lang/zls/tests/build_runner_cases/define_c_macro.zig --build-runner /home/adrian/.dev/pkg/zig_lang/zls/src/build_runner/build_runner.zig --cache-dir ./.zig-cache/ --global-cache-dir /home/adrian/.cache/zig/ --zig-lib-dir /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig/

Build Summary: 39/57 steps succeeded (8 failed); 572/583 tests passed (11 skipped)
test transitive failure
└─ test-build-runner transitive failure
   ├─ run build_runner_check (add_module.zig) transitive failure
   │  └─ run build runner (add_module.zig) failure
   ├─ run build_runner_check (define_c_macro.zig) transitive failure
   │  └─ run build runner (define_c_macro.zig) failure
   ├─ run build_runner_check (empty.zig) transitive failure
   │  └─ run build runner (empty.zig) failure
   ├─ run build_runner_check (module_root_source_file_collision.zig) transitive failure
   │  └─ run build runner (module_root_source_file_collision.zig) failure
   ├─ run build_runner_check (module_self_import.zig) transitive failure
   │  └─ run build runner (module_self_import.zig) failure
   ├─ run build_runner_check (multiple_module_import_names.zig) transitive failure
   │  └─ run build runner (multiple_module_import_names.zig) failure
   ├─ run build_runner_check (no_root_source_file.zig) transitive failure
   │  └─ run build runner (no_root_source_file.zig) failure
   └─ run build_runner_check (public_module_with_generated_file.zig) transitive failure
      └─ run build runner (public_module_with_generated_file.zig) failure

error: the following build command failed with exit code 1:
.zig-cache/o/92cdbcf6e6755e3d064182ea08fb6f16/build /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/bin/zig /home/adrian/.dev/pkg/zig_lang/zigroot/zig-out/lib/zig /home/adrian/.dev/pkg/zig_lang/zls .zig-cache /home/adrian/.cache/zig --seed 0x4af2ec8c -Zc990db5c2c42dfd6 test
```

6. `zig build check` also succeeds.

### Expected Behavior

`zls` on master should compile with `zig` on master. Hope this helps.
