### ISSUE TITLE
problem compiling latest build with 0.7.1 and 0.8.0 (latest build)

### ISSUE THREAD

**Issue by hgabe** [zigtools/zls#244]
I this message when I tried compiling zls with both 0.7.1 and 0.8.0

> .\src\document_store.zig:110:36: error: no member named 'shrinkAndFree' in struct 'std.array_list.ArrayListAlignedUnmanaged(document_store.Pkg,null)'
                build_file.packages.shrinkAndFree(allocator, 0);
                                   ^
.\src\document_store.zig:419:12: note: referenced here
        }) catch |err| {
           ^
.\src\main.zig:1193:5: note: referenced here
    try document_store.applySave(handle);
    ^
.\src\semantic_tokens.zig:95:12: error: enum 'std.builtin.CallingConvention' has no field named 'Inline'
) callconv(.Inline) !void {
           ^
C:\zig\lib\std\builtin.zig:153:31: note: 'std.builtin.CallingConvention' declared here
pub const CallingConvention = enum {
                              ^
.\src\semantic_tokens.zig:270:21: note: referenced here
                try writeToken(builder, block_node.label, .label);
                    ^
.\src\analysis.zig:202:26: error: expected optional type, found '*std.zig.ast.Node'
            return ((decl.name orelse return null).castTag(.StringLiteral) orelse return null).token;
                         ^
.\src\analysis.zig:202:32: note: referenced here
            return ((decl.name orelse return null).castTag(.StringLiteral) orelse return null).token;
                               ^
zls...The following command exited with error code 1:
C:\zig\zig.exe build-exe C:\zls2\src\main.zig --pkg-begin build_options C:\zls2\zig-cache\zls_build_options.zig --pkg-end -OReleaseSafe --cache-dir C:\zls2\zig-cache --global-cache-dir C:\Users\hgsba\AppData\Local\zig --name zls --pkg-begin known-folders C:\zls2\src\known-folders\known-folders.zig --pkg-end --enable-cache
error: the following build command failed with exit code 1:
C:\zls2\zig-cache\o\5a46f03cc1826362517cf7152e75e559\build.exe C:\zig\zig.exe C:\zls2 C:\zls2\zig-cache C:\Users\hgsba\AppData\Local\zig -Drelease-safe
