### ISSUE TITLE
ZLS fails to build with Zig 0.16.0-dev.1976+8e091047b

### ISSUE THREAD

**Issue by Durobot** [zigtools/zls#2554]
### Zig Version

0.16.0-dev.1976+8e091047b

### ZLS Version

26e019205cc7a3f583ce4ad6c25ef131a62d98c3

### Steps to Reproduce and Observed Behavior

Build with `zig build -Doptimize=ReleaseSafe`, compilation fails with:
```
$ zig build -Doptimize=ReleaseSafe
build.zig:348:65: error: union 'process.SpawnOptions.StdIo' has no member named 'Ignore'
    const git_describe_untrimmed = b.runAllowFail(argv, &code, .Ignore) catch |err| {
                                                               ~^~~~~~
/home/archie/.night.zig/zig-x86_64-linux-0.16.0-dev.1976+8e091047b/lib/std/process.zig:423:23: note: union declared here
    pub const StdIo = union(enum) {
                      ^~~~~
```

### Expected Behavior

Successful build

### Log Output

```shell

```

**Comment by Nanotwerp** [comment]
Will be fixed by https://github.com/zigtools/zls/pull/2556.
