### ISSUE TITLE
Fail to work with zig master 0.15.0-dev.848+f3940ad85 on Windows

### ISSUE THREAD

**Issue by IamSanjid** [zigtools/zls#2366]
### Zig Version

0.15.0-dev.848+f3940ad85

### ZLS Version

0.15.0-dev.203+706e08fc

### Client / Code Editor / Extensions

VS Code(vscode-zig) Zig Language

### Steps to Reproduce and Observed Behavior

Needs to address [commit](https://github.com/ziglang/zig/commit/f3c0555975053a6d3ffd9bc239b732658aebe5d6),
no `output_file` exists anymore.

Changes needed in these places I think:
`output_file` to `generated_dir`
https://github.com/zigtools/zls/blob/706e08fc80e6c21650f54e5aab91dbe8fb441f0f/src/build_runner/0.14.0.zig#L1077-L1079

and `output_file.getPath()` to `getOutputFile()`
https://github.com/zigtools/zls/blob/706e08fc80e6c21650f54e5aab91dbe8fb441f0f/src/build_runner/0.14.0.zig#L1152-L1154

### Expected Behavior

Should work normally.

### Relevant log output

```shell
C:\Users\User\AppData\Local\Temp\zls\build_runner\626a2e77993a5ebfd214e97067f99add\build_runner.zig:1078:79: error: no field named 'output_file' in struct 'Build.Step.ConfigHeader'
                        try set.put(allocator, include_dir.config_header_step.output_file.step, {});
```

**Comment by farhaven** [comment]
This is not just Windows, it also fails on Linux with `zig-x86_64-linux-0.15.0-dev.847+850655f0`

**Comment by IamSanjid** [comment]
> This is not just Windows, it also fails on Linux with `zig-x86_64-linux-0.15.0-dev.847+850655f0`

Of course it is I forgot to remove `on Windows` after I figured the root cause. But I will keep it still just because I tested it on windows only, I guess.
