### ISSUE TITLE
Output of check step not being reported

### ISSUE THREAD

**Issue by yamafaktory** [zigtools/zls#2562]
### Zig Version

0.16.0-dev.2135+7c0b42ba0

### ZLS Version

0.16.0-dev.104+d732b05e

### Client / Code Editor / Extensions

NVIM v0.11.5

### Steps to Reproduce and Observed Behavior

Use this check step: https://github.com/yamafaktory/hypergraphz/blob/main/build.zig#L53-L58

-> works fine with tagged version (0.15.2)
-> doesn't work with aforementioned zls & zig version though manually triggering `zig build check` works as expected

### Expected Behavior

zls should report any error from the check step.

### Log Output

```shell
1 │ warn  ( diag ): zig build runner exited with non-zero status: 2
   2 │ stderr:
   3 │ /home/davy/.cache/zls/build_runner/4f1e08bb76182aa6412cc0242f77ddd6/build_runner.zig:34:6: error: no field named 'crypto_fork_safety' in struct 'std.Opti
     │ ons'
   4 │     .crypto_fork_safety = false,
   5 │      ^~~~~~~~~~~~~~~~~~
   6 │ /home/davy/.zvm/master/lib/std/std.zig:114:21: note: struct declared here
   7 │ pub const Options = struct {
   8 │                     ^~~~~~
   9 │ referenced by:
  10 │     options: /home/davy/.zvm/master/lib/std/std.zig:112:69
  11 │     print__anon_4314: /home/davy/.zvm/master/lib/std/Io/Writer.zig:712:24
  12 │     3 reference(s) hidden; use '-freference-trace=5' to see all references
```

**Comment by xdBronch** [comment]
the log output is showing exactly why its not working. in order to get the errors from your check step ZLS needs to be able to build the project, and as is shown, it cant. updating your ZLS should fix this

**Comment by yamafaktory** [comment]
I tried to checkout this repo directly, build zls locally and replace the bin I got from zvm with the built one. Still not working.

**Comment by xdBronch** [comment]
what version did you try to build? it was just fixed this morning b60243ff9588258047179eb9590f162828271bb9
whats the output on the new version?

**Comment by yamafaktory** [comment]
```sh
warn  ( diag ): zig build runner exited with non-zero status: 2
stderr:
/home/davy/.cache/zls/build_runner/fc59a6ffeb01498932e06c7ff25ff3aa/build_runner.zig:462:56: error: no field or member function named 'recursiveReset' in 'Build.Step'
        .dependency_failure, .failure, .skipped => step.recursiveReset(gpa),
                                                   ~~~~^~~~~~~~~~~~~~~
/home/davy/.zvm/master/lib/std/Build/Step.zig:1:1: note: struct declared here
const Step = @This();
^~~~~
/home/davy/.cache/zls/build_runner/fc59a6ffeb01498932e06c7ff25ff3aa/build_runner.zig:462:56: note: method invocation only supports up to one level of implicit pointer dereferencing
/home/davy/.cache/zls/build_runner/fc59a6ffeb01498932e06c7ff25ff3aa/build_runner.zig:462:56: note: use '.*' to dereference pointer
referenced by:
    main: /home/davy/.cache/zls/build_runner/fc59a6ffeb01498932e06c7ff25ff3aa/build_runner.zig:449:37
    callMain [inlined]: /home/davy/.zvm/master/lib/std/start.zig:676:88
    callMainWithArgs [inlined]: /home/davy/.zvm/master/lib/std/start.zig:626:20
    posixCallMainAndExit: /home/davy/.zvm/master/lib/std/start.zig:581:38
    2 reference(s) hidden; use '-freference-trace=6' to see all references
/home/davy/.cache/zls/build_runner/fc59a6ffeb01498932e06c7ff25ff3aa/build_runner.zig:540:25: error: no field or member function named 'recursiveReset' in 'Build.Step'
            else => step.recursiveReset(gpa),
                    ~~~~^~~~~~~~~~~~~~~
/home/davy/.zvm/master/lib/std/Build/Step.zig:1:1: note: struct declared here
const Step = @This();
^~~~~
/home/davy/.cache/zls/build_runner/fc59a6ffeb01498932e06c7ff25ff3aa/build_runner.zig:540:25: note: method invocation only supports up to one level of implicit pointer dereferencing
/home/davy/.cache/zls/build_runner/fc59a6ffeb01498932e06c7ff25ff3aa/build_runner.zig:540:25: note: use '.*' to dereference pointer
/home/davy/.cache/zls/build_runner/fc59a6ffeb01498932e06c7ff25ff3aa/build_runner.zig:717:10: error: no field named 'running' in enum 'Build.Step.State'
        .running,
        ~^~~~~~~
/home/davy/.zvm/master/lib/std/Build/Step.zig:125:19: note: enum declared here
pub const State = enum {
                  ^~~~
/home/davy/.cache/zls/build_runner/fc59a6ffeb01498932e06c7ff25ff3aa/build_runner.zig:747:30: error: no field named 'running' in enum 'Build.Step.State'
            .precheck_done, .running => {
                            ~^~~~~~~
/home/davy/.zvm/master/lib/std/Build/Step.zig:125:19: note: enum declared here
pub const State = enum {
                  ^~~~
```

**Comment by xdBronch** [comment]
agh looks like there was yet another breaking change <https://codeberg.org/ziglang/zig/pulls/30754> 😄, you'll just have to downgrade your zig version or wait a bit for zls to be updated

**Comment by yamafaktory** [comment]
Thanks a lot for the swift feedback @xdBronch !

Feel free to close this issue :)

**Comment by techatrix** [comment]
Fixed by #2560 or #2569 depending on the Zig version
