### ISSUE TITLE
zig build fails with 'no member named use_stage1'

### ISSUE THREAD

**Issue by ysgard** [zigtools/zls#633]
On Linux (Fedora 36) using zig 0.9.1, using a completely fresh copy of zls.

```sh
➜  git clone --recurse-submodules https://github.com/zigtools/zls
Cloning into 'zls'...
<snip>
➜  cd zls
➜  zig build -Drelease-safe
./build.zig:12:8: error: no member named 'use_stage1' in struct 'std.build.LibExeObjStep'
    exe.use_stage1 = true;
       ^
```

**Comment by truemedian** [comment]
zls only builds with the master branch of zig, zls does not work with 0.9.1

**Comment by ysgard** [comment]
Ah :facepalm: I missed that part. Thank you, and I'm sorry.

**Comment by annymosse** [comment]
Hello there, I'm a new user and I'm using zig in my android device for playground tests, `zls` isn't working and provide same error, @truemedian  what do you advice me to do to make it work ?
(Note : `zls` work very well in my PC).

**Comment by annymosse** [comment]
@nektro https://ziglang.org/download/ doesn't include `armv7a` architecture for (version 0.10.x) so I can't build current `zls` master with `zig 0.9.1` from my Android device.

**Comment by nektro** [comment]
in that case you'd have to cross compile zig on your desktop or wait for the `0.10.0` release happening on nov 1

**Comment by annymosse** [comment]
@nektro I'm so excited to start using it, Hopefully `zigtools/zls` will provide a pre-built version of `zls` for `arm` archs in the future.

**Comment by annymosse** [comment]
@Vexu ohh my bad 🤦🏻‍♂️ ; I forgot that I can use my laptop to compile `zls` to `arm arch` using already pre-built `zig version 0.10.0`, @Vexu thank you to remind me so much.

**Comment by DavidTheBugWriter** [comment]
I'm also having this issue, however my Zig version is 0.11.0-dev.617+1310ef757. I assume zls still only builds against Master. However a previous error for installing against  zig 0.10.0 said 

>thread 8725807 panic: Your Zig version v0.10.0 does not meet the minimum build requirement of v0.11.0-dev.399+44ee1c885
/Users/david/projects/learning_language/zig/zls/build.zig:10:62: 0x1086c5720 in build (build)
    if (current_zig.order(min_zig).compare(.lt)) @panic(b.fmt("Your Zig version v{} does not meet the minimum build requirement of v{}", .{ current_zig, min_zig }));
                                                             ^
/usr/local/Cellar/zig/0.10.0/lib/zig/build_runner.zig:231:38: 0x1086b5ec0 in runBuild (build)
        .ErrorUnion => try root.build(builder),
                                     ^
/usr/local/Cellar/zig/0.10.0/lib/zig/build_runner.zig:212:17: 0x1086b269f in main (build)
    try runBuild(builder);
                ^
/usr/local/Cellar/zig/0.10.0/lib/zig/std/start.zig:606:37: 0x1086b6264 in main (build)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x108a2b52d in ??? (???)
???:?:?: 0x0 in ??? (???)
error: the following build command crashed:
/Users/david/projects/learning_language/zig/zls/zig-cache/o/b1626255d8050f0ae864bf7bcd41ec60/build /usr/local/Cellar/zig/0.10.0/bin/zig /Users/david/projects/learning_language/zig/zls /Users/david/projects/learning_language/zig/zls/zig-cache /Users/david/.cache/zig -Drelease-fast
```

Soooo I'm a bit stuck.

**Comment by SuperAuguste** [comment]
See https://github.com/ziglang/zig/pull/13560. I'll fix this tonight.
